[profile.default]
src = "src"
out = "out"
ffi = true
ast = true
build_info = true
libs = ["lib"]
evm_version = "cancun"
remappings = [
    '@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@openzeppelin/contracts-upgradeable-4.7.3/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/',
    '@chainlink/=lib/foundry-chainlink-toolkit/src',
    '@chainlink-contracts/=lib/foundry-chainlink-toolkit/lib/chainlink-brownie-contracts/contracts/src/v0.8/'
]

[fmt]
line_length = 120
tab_width = 4
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
