[profile.default]
src = "src"
out = "out"
ffi = true
ast = true
build_info = true
libs = ["lib"]
evm_version = "cancun"
remappings = [
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@openzeppelin/contracts-upgradeable-4.7.3/=lib/openzeppelin-contracts-upgradeable/contracts/'
]

[fmt]
line_length = 160
tab_width = 4
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
